export const countriesList = [
	{ label: "Afghanistan", code: "AF", value: "AF" },
	{ label: "Albania", code: "AL", value: "AL" },
	{ label: "Algeria", code: "DZ", value: "DZ" },
	{ label: "Andorra", code: "AD", value: "AD" },
	{ label: "Angola", code: "AO", value: "AO" },
	{ label: "Antigua and Barbuda", code: "AG", value: "AG" },
	{ label: "Argentina", code: "AR", value: "AR" },
	{ label: "Armenia", code: "AM", value: "AM" },
	{ label: "Australia", code: "AU", value: "AU" },
	{ label: "Austria", code: "AT", value: "AT" },
	{ label: "Azerbaijan", code: "AZ", value: "AZ" },
	{ label: "Bahamas", code: "BS", value: "BS" },
	{ label: "Bahrain", code: "BH", value: "BH" },
	{ label: "Bangladesh", code: "BD", value: "BD" },
	{ label: "Barbados", code: "BB", value: "BB" },
	{ label: "Belarus", code: "BY", value: "BY" },
	{ label: "Belgium", code: "BE", value: "BE" },
	{ label: "Belize", code: "BZ", value: "BZ" },
	{ label: "Benin", code: "BJ", value: "BJ" },
	{ label: "Bhutan", code: "BT", value: "BT" },
	{ label: "Bolivia", code: "BO", value: "BO" },
	{ label: "Bosnia and Herzegovina", code: "BA", value: "BA" },
	{ label: "Botswana", code: "BW", value: "BW" },
	{ label: "Brazil", code: "BR", value: "BR" },
	{ label: "Brunei", code: "BN", value: "BN" },
	{ label: "Bulgaria", code: "BG", value: "BG" },
	{ label: "Burkina Faso", code: "BF", value: "BF" },
	{ label: "Burundi", code: "BI", value: "BI" },
	{ label: "Cabo Verde", code: "CV", value: "CV" },
	{ label: "Cambodia", code: "KH", value: "KH" },
	{ label: "Cameroon", code: "CM", value: "CM" },
	{ label: "Canada", code: "CA", value: "CA" },
	{ label: "Central African Republic", code: "CF", value: "CF" },
	{ label: "Chad", code: "TD", value: "TD" },
	{ label: "Chile", code: "CL", value: "CL" },
	{ label: "China", code: "CN", value: "CN" },
	{ label: "Colombia", code: "CO", value: "CO" },
	{ label: "Comoros", code: "KM", value: "KM" },
	{ label: "Congo (Congo-Brazzaville)", code: "CG", value: "CG" },
	{ label: "Costa Rica", code: "CR", value: "CR" },
	{ label: "Croatia", code: "HR", value: "HR" },
	{ label: "Cuba", code: "CU", value: "CU" },
	{ label: "Cyprus", code: "CY", value: "CY" },
	{ label: "Czechia", code: "CZ", value: "CZ" },
	{ label: "Democratic Republic of the Congo", code: "CD", value: "CD" },
	{ label: "Denmark", code: "DK", value: "DK" },
	{ label: "Djibouti", code: "DJ", value: "DJ" },
	{ label: "Dominica", code: "DM", value: "DM" },
	{ label: "Dominican Republic", code: "DO", value: "DO" },
	{ label: "Ecuador", code: "EC", value: "EC" },
	{ label: "Egypt", code: "EG", value: "EG" },
	{ label: "El Salvador", code: "SV", value: "SV" },
	{ label: "Equatorial Guinea", code: "GQ", value: "GQ" },
	{ label: "Eritrea", code: "ER", value: "ER" },
	{ label: "Estonia", code: "EE", value: "EE" },
	{ label: "Eswatini", code: "SZ", value: "SZ" },
	{ label: "Ethiopia", code: "ET", value: "ET" },
	{ label: "Fiji", code: "FJ", value: "FJ" },
	{ label: "Finland", code: "FI", value: "FI" },
	{ label: "France", code: "FR", value: "FR" },
	{ label: "Gabon", code: "GA", value: "GA" },
	{ label: "Gambia", code: "GM", value: "GM" },
	{ label: "Georgia", code: "GE", value: "GE" },
	{ label: "Germany", code: "DE", value: "DE" },
	{ label: "Ghana", code: "GH", value: "GH" },
	{ label: "Greece", code: "GR", value: "GR" },
	{ label: "Grenada", code: "GD", value: "GD" },
	{ label: "Guatemala", code: "GT", value: "GT" },
	{ label: "Guinea", code: "GN", value: "GN" },
	{ label: "Guinea-Bissau", code: "GW", value: "GW" },
	{ label: "Guyana", code: "GY", value: "GY" },
	{ label: "Haiti", code: "HT", value: "HT" },
	{ label: "Holy See", code: "VA", value: "VA" },
	{ label: "Honduras", code: "HN", value: "HN" },
	{ label: "Hungary", code: "HU", value: "HU" },
	{ label: "Iceland", code: "IS", value: "IS" },
	{ label: "India", code: "IN", value: "IN" },
	{ label: "Indonesia", code: "ID", value: "ID" },
	{ label: "Iran", code: "IR", value: "IR" },
	{ label: "Iraq", code: "IQ", value: "IQ" },
	{ label: "Ireland", code: "IE", value: "IE" },
	{ label: "Israel", code: "IL", value: "IL" },
	{ label: "Italy", code: "IT", value: "IT" },
	{ label: "Ivory Coast", code: "CI", value: "CI" },
	{ label: "Jamaica", code: "JM", value: "JM" },
	{ label: "Japan", code: "JP", value: "JP" },
	{ label: "Jordan", code: "JO", value: "JO" },
	{ label: "Kazakhstan", code: "KZ", value: "KZ" },
	{ label: "Kenya", code: "KE", value: "KE" },
	{ label: "Kiribati", code: "KI", value: "KI" },
	{ label: "Kuwait", code: "KW", value: "KW" },
	{ label: "Kyrgyzstan", code: "KG", value: "KG" },
	{ label: "Laos", code: "LA", value: "LA" },
	{ label: "Latvia", code: "LV", value: "LV" },
	{ label: "Lebanon", code: "LB", value: "LB" },
	{ label: "Lesotho", code: "LS", value: "LS" },
	{ label: "Liberia", code: "LR", value: "LR" },
	{ label: "Libya", code: "LY", value: "LY" },
	{ label: "Liechtenstein", code: "LI", value: "LI" },
	{ label: "Lithuania", code: "LT", value: "LT" },
	{ label: "Luxembourg", code: "LU", value: "LU" },
	{ label: "Madagascar", code: "MG", value: "MG" },
	{ label: "Malawi", code: "MW", value: "MW" },
	{ label: "Malaysia", code: "MY", value: "MY" },
	{ label: "Maldives", code: "MV", value: "MV" },
	{ label: "Mali", code: "ML", value: "ML" },
	{ label: "Malta", code: "MT", value: "MT" },
	{ label: "Marshall Islands", code: "MH", value: "MH" },
	{ label: "Mauritania", code: "MR", value: "MR" },
	{ label: "Mauritius", code: "MU", value: "MU" },
	{ label: "Mexico", code: "MX", value: "MX" },
	{ label: "Micronesia", code: "FM", value: "FM" },
	{ label: "Moldova", code: "MD", value: "MD" },
	{ label: "Monaco", code: "MC", value: "MC" },
	{ label: "Mongolia", code: "MN", value: "MN" },
	{ label: "Montenegro", code: "ME", value: "ME" },
	{ label: "Morocco", code: "MA", value: "MA" },
	{ label: "Mozambique", code: "MZ", value: "MZ" },
	{ label: "Myanmar", code: "MM", value: "MM" },
	{ label: "Namibia", code: "NA", value: "NA" },
	{ label: "Nauru", code: "NR", value: "NR" },
	{ label: "Nepal", code: "NP", value: "NP" },
	{ label: "Netherlands", code: "NL", value: "NL" },
	{ label: "New Zealand", code: "NZ", value: "NZ" },
	{ label: "Nicaragua", code: "NI", value: "NI" },
	{ label: "Niger", code: "NE", value: "NE" },
	{ label: "Nigeria", code: "NG", value: "NG" },
	{ label: "North Korea", code: "KP", value: "KP" },
	{ label: "North Macedonia", code: "MK", value: "MK" },
	{ label: "Norway", code: "NO", value: "NO" },
	{ label: "Oman", code: "OM", value: "OM" },
	{ label: "Pakistan", code: "PK", value: "PK" },
	{ label: "Palau", code: "PW", value: "PW" },
	{ label: "Palestine", code: "PS", value: "PS" },
	{ label: "Panama", code: "PA", value: "PA" },
	{ label: "Papua New Guinea", code: "PG", value: "PG" },
	{ label: "Paraguay", code: "PY", value: "PY" },
	{ label: "Peru", code: "PE", value: "PE" },
	{ label: "Philippines", code: "PH", value: "PH" },
	{ label: "Poland", code: "PL", value: "PL" },
	{ label: "Portugal", code: "PT", value: "PT" },
	{ label: "Qatar", code: "QA", value: "QA" },
	{ label: "Romania", code: "RO", value: "RO" },
	{ label: "Russia", code: "RU", value: "RU" },
	{ label: "Rwanda", code: "RW", value: "RW" },
	{ label: "Saint Kitts and Nevis", code: "KN", value: "KN" },
	{ label: "Saint Lucia", code: "LC", value: "LC" },
	{ label: "Saint Vincent and the Grenadines", code: "VC", value: "VC" },
	{ label: "Samoa", code: "WS", value: "WS" },
	{ label: "San Marino", code: "SM", value: "SM" },
	{ label: "Sao Tome and Principe", code: "ST", value: "ST" },
	{ label: "Saudi Arabia", code: "SA", value: "SA" },
	{ label: "Senegal", code: "SN", value: "SN" },
	{ label: "Serbia", code: "RS", value: "RS" },
	{ label: "Seychelles", code: "SC", value: "SC" },
	{ label: "Sierra Leone", code: "SL", value: "SL" },
	{ label: "Singapore", code: "SG", value: "SG" },
	{ label: "Slovakia", code: "SK", value: "SK" },
	{ label: "Slovenia", code: "SI", value: "SI" },
	{ label: "Solomon Islands", code: "SB", value: "SB" },
	{ label: "Somalia", code: "SO", value: "SO" },
	{ label: "South Africa", code: "ZA", value: "ZA" },
	{ label: "South Korea", code: "KR", value: "KR" },
	{ label: "South Sudan", code: "SS", value: "SS" },
	{ label: "Spain", code: "ES", value: "ES" },
	{ label: "Sri Lanka", code: "LK", value: "LK" },
	{ label: "Sudan", code: "SD", value: "SD" },
	{ label: "Surilabel", code: "SR", value: "SR" },
	{ label: "Sweden", code: "SE", value: "SE" },
	{ label: "Switzerland", code: "CH", value: "CH" },
	{ label: "Syria", code: "SY", value: "SY" },
	{ label: "Taiwan", code: "TW", value: "TW" },
	{ label: "Tajikistan", code: "TJ", value: "TJ" },
	{ label: "Tanzania", code: "TZ", value: "TZ" },
	{ label: "Thailand", code: "TH", value: "TH" },
	{ label: "Timor-Leste", code: "TL", value: "TL" },
	{ label: "Togo", code: "TG", value: "TG" },
	{ label: "Tonga", code: "TO", value: "TO" },
	{ label: "Trinidad and Tobago", code: "TT", value: "TT" },
	{ label: "Tunisia", code: "TN", value: "TN" },
	{ label: "Turkey", code: "TR", value: "TR" },
	{ label: "Turkmenistan", code: "TM", value: "TM" },
	{ label: "Tuvalu", code: "TV", value: "TV" },
	{ label: "Uganda", code: "UG", value: "UG" },
	{ label: "Ukraine", code: "UA", value: "UA" },
	{ label: "United Arab Emirates", code: "AE", value: "AE" },
	{ label: "United Kingdom", code: "GB", value: "GB" },
	{ label: "United States of America", code: "US", value: "US" },
	{ label: "Uruguay", code: "UY", value: "UY" },
	{ label: "Uzbekistan", code: "UZ", value: "UZ" },
	{ label: "Vanuatu", code: "VU", value: "VU" },
	{ label: "Venezuela", code: "VE", value: "VE" },
	{ label: "Vietnam", code: "VN", value: "VN" },
	{ label: "Yemen", code: "YE", value: "YE" },
	{ label: "Zambia", code: "ZM", value: "ZM" },
	{ label: "Zimbabwe", code: "ZW", value: "ZW" },
];
export const flags = {
	AF: "🇦🇫",
	AL: "🇦🇱",
	DZ: "🇩🇿",
	AD: "🇦🇩",
	AO: "🇦🇴",
	AG: "🇦🇬",
	AR: "🇦🇷",
	AM: "🇦🇲",
	AU: "🇦🇺",
	AT: "🇦🇹",
	AZ: "🇦🇿",
	BS: "🇧🇸",
	BH: "🇧🇭",
	BD: "🇧🇩",
	BB: "🇧🇧",
	BY: "🇧🇾",
	BE: "🇧🇪",
	BZ: "🇧🇿",
	BJ: "🇧🇯",
	BT: "🇧🇹",
	BO: "🇧🇴",
	BA: "🇧🇦",
	BW: "🇧🇼",
	BR: "🇧🇷",
	BN: "🇧🇳",
	BG: "🇧🇬",
	BF: "🇧🇫",
	BI: "🇧🇮",
	CV: "🇨🇻",
	KH: "🇰🇭",
	CM: "🇨🇲",
	CA: "🇨🇦",
	CF: "🇨🇫",
	TD: "🇹🇩",
	CL: "🇨🇱",
	CN: "🇨🇳",
	CO: "🇨🇴",
	KM: "🇰🇲",
	CG: "🇨🇬",
	CR: "🇨🇷",
	HR: "🇭🇷",
	CU: "🇨🇺",
	CY: "🇨🇾",
	CZ: "🇨🇿",
	CD: "🇨🇩",
	DK: "🇩🇰",
	DJ: "🇩🇯",
	DM: "🇩🇲",
	DO: "🇩🇴",
	EC: "🇪🇨",
	EG: "🇪🇬",
	SV: "🇸🇻",
	GQ: "🇬🇶",
	ER: "🇪🇷",
	EE: "🇪🇪",
	SZ: "🇸🇿",
	ET: "🇪🇹",
	FJ: "🇫🇯",
	FI: "🇫🇮",
	FR: "🇫🇷",
	GA: "🇬🇦",
	GM: "🇬🇲",
	GE: "🇬🇪",
	DE: "🇩🇪",
	GH: "🇬🇭",
	GR: "🇬🇷",
	GD: "🇬🇩",
	GT: "🇬🇹",
	GN: "🇬🇳",
	GW: "🇬🇼",
	GY: "🇬🇾",
	HT: "🇭🇹",
	VA: "🇻🇦",
	HN: "🇭🇳",
	HU: "🇭🇺",
	IS: "🇮🇸",
	IN: "🇮🇳",
	ID: "🇮🇩",
	IR: "🇮🇷",
	IQ: "🇮🇶",
	IE: "🇮🇪",
	IL: "🇮🇱",
	IT: "🇮🇹",
	CI: "🇨🇮",
	JM: "🇯🇲",
	JP: "🇯🇵",
	JO: "🇯🇴",
	KZ: "🇰🇿",
	KE: "🇰🇪",
	KI: "🇰🇮",
	KW: "🇰🇼",
	KG: "🇰🇬",
	LA: "🇱🇦",
	LV: "🇱🇻",
	LB: "🇱🇧",
	LS: "🇱🇸",
	LR: "🇱🇷",
	LY: "🇱🇾",
	LI: "🇱🇮",
	LT: "🇱🇹",
	LU: "🇱🇺",
	MG: "🇲🇬",
	MW: "🇲🇼",
	MY: "🇲🇾",
	MV: "🇲🇻",
	ML: "🇲🇱",
	MT: "🇲🇹",
	MH: "🇲🇭",
	MR: "🇲🇷",
	MU: "🇲🇺",
	MX: "🇲🇽",
	FM: "🇫🇲",
	MD: "🇲🇩",
	MC: "🇲🇨",
	MN: "🇲🇳",
	ME: "🇲🇪",
	MA: "🇲🇦",
	MZ: "🇲🇿",
	MM: "🇲🇲",
	NA: "🇳🇦",
	NR: "🇳🇷",
	NP: "🇳🇵",
	NL: "🇳🇱",
	NZ: "🇳🇿",
	NI: "🇳🇮",
	NE: "🇳🇪",
	NG: "🇳🇬",
	KP: "🇰🇵",
	MK: "🇲🇰",
	NO: "🇳🇴",
	OM: "🇴🇲",
	PK: "🇵🇰",
	PW: "🇵🇼",
	PS: "🇵🇸",
	PA: "🇵🇦",
	PG: "🇵🇬",
	PY: "🇵🇾",
	PE: "🇵🇪",
	PH: "🇵🇭",
	PL: "🇵🇱",
	PT: "🇵🇹",
	QA: "🇶🇦",
	RO: "🇷🇴",
	RU: "🇷🇺",
	RW: "🇷🇼",
	KN: "🇰🇳",
	LC: "🇱🇨",
	VC: "🇻🇨",
	WS: "🇼🇸",
	SM: "🇸🇲",
	ST: "🇸🇹",
	SA: "🇸🇦",
	SN: "🇸🇳",
	RS: "🇷🇸",
	SC: "🇸🇨",
	SL: "🇸🇱",
	SG: "🇸🇬",
	SK: "🇸🇰",
	SI: "🇸🇮",
	SB: "🇸🇧",
	SO: "🇸🇴",
	ZA: "🇿🇦",
	KR: "🇰🇷",
	SS: "🇸🇸",
	ES: "🇪🇸",
	LK: "🇱🇰",
	SD: "🇸🇩",
	SR: "🇸🇷",
	SE: "🇸🇪",
	CH: "🇨🇭",
	SY: "🇸🇾",
	TW: "🇹🇼",
	TJ: "🇹🇯",
	TZ: "🇹🇿",
	TH: "🇹🇭",
	TL: "🇹🇱",
	TG: "🇹🇬",
	TO: "🇹🇴",
	TT: "🇹🇹",
	TN: "🇹🇳",
	TR: "🇹🇷",
	TM: "🇹🇲",
	TV: "🇹🇻",
	UG: "🇺🇬",
	UA: "🇺🇦",
	AE: "🇦🇪",
	GB: "🇬🇧",
	US: "🇺🇸",
	UY: "🇺🇾",
	UZ: "🇺🇿",
	VU: "🇻🇺",
	VE: "🇻🇪",
	VN: "🇻🇳",
	YE: "🇾🇪",
	ZM: "🇿🇲",
	ZW: "🇿🇼",
};
