export const interestList = [
	{ label: "Adventure", value: "adventure" },
	{ label: "Fantasy", value: "fantasy" },
	{ label: "Science Fiction", value: "sci-fi" },
	{ label: "Romance", value: "romance" },
	{ label: "Mystery", value: "mystery" },
	{ label: "Thriller", value: "thriller" },
	{ label: "Horror", value: "horror" },
	{ label: "Historical Fiction", value: "historical fiction" },
	{ label: "Poetry", value: "poetry" },
	{ label: "Comedy", value: "comedy" },
	{ label: "Drama", value: "drama" },
	{ label: "Action", value: "action" },
	{ label: "Dystopian", value: "dystopian" },
	{ label: "Paranormal", value: "paranormal" },
	{ label: "Young Adult", value: "young adult" },
];

export const preferenceList = [
	{ label: "Writing", value: "writing" },
	{ label: "Editing", value: "editing" },
	{ label: "Proofreading", value: "proofreading" },
	{ label: "Ideation", value: "ideation" },
	{ label: "Worldbuilding", value: "worldbuilding" },
	{ label: "Character Development", value: "character development" },
	{ label: "Plotting", value: "plotting" },
	{ label: "Outlining", value: "outlining" },
	{ label: "Collaboration", value: "collaboration" },
	{ label: "Feedback", value: "feedback" },
	{ label: "Storytelling", value: "storytelling" },
	{ label: "Research", value: "research" },
	{ label: "Formatting", value: "formatting" },
	{ label: "Cover Design", value: "cover design" },
];
