export const languages = [
	{ label: "Mandarin Chinese", value: "Chinese (Simplified)" },
	{ label: "Spanish", value: "Español" },
	{ label: "English", value: "English" },
	{ label: "Hindi", value: "हिन्दी" },
	{ label: "Bengali", value: "বাংলা" },
	{ label: "Portuguese", value: "Português" },
	{ label: "Norwegian", value: "Norsk (Bokmål)" },
	{ label: "Russian", value: "Русский" },
	{ label: "Japanese", value: "日本語" },
	{ label: "Western Punjabi", value: "پنجابی" },
	{ label: "Marathi", value: "मराठी" },
	{ label: "Telugu", value: "తెలుగు" },
	{ label: "Wu Chinese", value: "Chinese (Wu)" },
	{ label: "Turkish", value: "Türkçe" },
	{ label: "Korean", value: "한국어" },
	{ label: "French", value: "Français" },
	{ label: "German", value: "Deutsch" },
	{ label: "Vietvaluese", value: "Tiếng Việt" },
	{ label: "Tamil", value: "தமிழ்" },
	{ label: "Yue Chinese", value: "Chinese (Yue)" },
	{ label: "Urdu", value: "اردو" },
	{ label: "Javanese", value: "Basa Jawa" },
	{ label: "Italian", value: "Italiano" },
	{ label: "Egyptian Arabic", value: "العربية المصرية" },
	{ label: "Gujarati", value: "ગુજરાતી" },
	{ label: "Iranian Persian", value: "فارسی" },
	{ label: "Bhojpuri", value: "भोजपुरी" },
	{ label: "Min Nan Chinese", value: "Chinese (Min Nan)" },
	{ label: "Hakka Chinese", value: "Chinese (Hakka)" },
	{ label: "Jin Chinese", value: "Chinese (Jin)" },
	{ label: "Hausa", value: "هَوُسَ" },
	{ label: "Kannada", value: "ಕನ್ನಡ" },
	{ label: "Indonesian", value: "Bahasa Indonesia" },
	{ label: "Polish", value: "Polski" },
	{ label: "Yoruba", value: "Yorùbá" },
	{ label: "Maithili", value: "मैथिली" },
	{ label: "Malayalam", value: "മലയാളം" },
	{ label: "Burmese", value: "မြန်မာဘာသာ" },
	{ label: "Sudanese Arabic", value: "العربية السودانية" },
	{ label: "Ukrainian", value: "Українська" },
	{ label: "Igbo", value: "Igbo" },
	{ label: "Northern Uzbek", value: "Ўзбек" },
	{ label: "Northern Pashto", value: "پښتو" },
	{ label: "Tagalog", value: "Tagalog" },
	{ label: "Southern Uzbek", value: "Ўзбек" },
	{ label: "Sindhi", value: "سنڌي" },
	{ label: "Nigerian Fulfulde", value: "Fulfulde" },
	{ label: "North Levantine Arabic", value: "العربية الشامية" },
	{ label: "Romanian", value: "Română" },
	{ label: "Dutch", value: "Nederlands" },
	{ label: "Saʽidi Arabic", value: "العربية السعيدية" },
	{ label: "Gan Chinese", value: "Chinese (Gan)" },
	{ label: "Southern Pashto", value: "پښتو" },
	{ label: "Serbo-Croatian", value: "Srpskohrvatski" },
	{ label: "Cebuano", value: "Sinugboanong Binisaya" },
	{ label: "Chhattisgarhi", value: "छत्तीसगढ़ी" },
	{ label: "Eastern Punjabi", value: "پنجابی" },
	{ label: "Haryanvi", value: "हरियाणवी" },
	{ label: "Hungarian", value: "Magyar" },
	{ label: "Chittagonian", value: "চাটগাঙ্গিয়া" },
	{ label: "Greek", value: "Ελληνικά" },
	{ label: "Somali", value: "Af-Soomaali" },
	{ label: "Chewa", value: "Chichewa" },
	{ label: "Deccan", value: "Dakhini" },
	{ label: "Zulu", value: "isiZulu" },
	{ label: "Czech", value: "Čeština" },
	{ label: "Kinyarwanda", value: "Kinyarwanda" },
	{ label: "Dhundhari", value: "धुन्धारी" },
	{ label: "Haitian Creole", value: "Kreyòl Ayisyen" },
	{ label: "Greek Cypriot", value: "Ελληνικά Κυπριακά" },
	{ label: "Tigrinya", value: "ትግርኛ" },
	{ label: "Kirundi", value: "Ikirundi" },
	{ label: "Eastern Min", value: "Chinese (Min Dong)" },
	{ label: "Swedish", value: "Svenska" },
	{ label: "Siwu", value: "Akʊposɛ" },
	{ label: "Bhojpur Bajjika", value: "भोजपुर भज्जिका" },
	{ label: "Latin", value: "Latina" },
	{ label: "Kosovar Albanian", value: "Shqip" },
	{ label: "Tswana", value: "Setswana" },
	{ label: "Balochi", value: "بلوچی" },
	{ label: "Sinhalese", value: "සිංහල" },
	{ label: "Tajik", value: "тоҷикӣ" },
	{ label: "Yi", value: "ꆇꉙ" },
	{ label: "Kanuri", value: "Kanuri" },
	{ label: "Uyghur", value: "ئۇيغۇرچە" },
	{ label: "Sindhi Saraiki", value: "سرائیکی" },
	{ label: "Nigerian Sign Language", value: "NSL" },
	{ label: "Dinka", value: "Thuɔŋjäŋ" },
	{ label: "Dangme", value: "Dangme" },
	{ label: "Greek Macedonian", value: "Ελληνικά Μακεδονικά" },
	{ label: "Amharic", value: "አማርኛ" },
	{ label: "Western Frisian", value: "Frysk" },
	{ label: "Kyrgyz", value: "Кыргызча" },
	{ label: "Serer", value: "Seereer" },
	{ label: "Kpelle", value: "Kpɛlɛ" },
	{ label: "Kongo", value: "KiKongo" },
	{ label: "Chamorro", value: "Chamoru" },
	{ label: "Bench", value: "ቤንች" },
	{ label: "Arabic", value: "العربية" },
	{ label: "Swahili", value: "Kiswahili" },
	{ label: "Amharic", value: "አማርኛ" },
	{ label: "Yoruba", value: "Yorùbá" },
	{ label: "Igbo", value: "Igbo" },
	{ label: "Hausa", value: "هَوُسَ" },
	{ label: "Oromo", value: "Oromiffa" },
	{ label: "Berber", value: "Berber" },
	{ label: "Zulu", value: "isiZulu" },
	{ label: "Shona", value: "chiShona" },
	{ label: "Akan", value: "Akan" },
	{ label: "Somali", value: "Af-Soomaali" },
	{ label: "Kinyarwanda", value: "Kinyarwanda" },
	{ label: "Wolof", value: "Wolof" },
	{ label: "Ibibio", value: "Ibibio-Efik" },
	{ label: "Fula", value: "Fulfulde" },
	{ label: "Tigrinya", value: "ትግርኛ" },
	{ label: "Sango", value: "Sängö" },
	{ label: "Luganda", value: "Luganda" },
	{ label: "Kikuyu", value: "Gĩkũyũ" },
	{ label: "Kanuri", value: "Kanuri" },
	{ label: "Tsonga", value: "Xitsonga" },
	{ label: "Chichewa", value: "Chichewa" },
	{ label: "Sotho", value: "Sesotho" },
	{ label: "Sesotho sa Leboa", value: "Sepedi" },
	{ label: "Tswana", value: "Setswana" },
	{ label: "Kirundi", value: "Ikirundi" },
	{ label: "SiSwati", value: "SiSwati" },
	{ label: "Bemba", value: "Ichibemba" },
	{ label: "Mandinka", value: "Mandinka" },
	{ label: "Sarekole", value: "Sarekole" },
	{ label: "Jola-Fonyi", value: "Jola-Fonyi" },
	{ label: "Jola", value: "Jola" },
	{ label: "Cantonese", value: "廣東話" },
];
